db:
  username: "postgres"
  password: "secre"
  host: "localhost"
  port: "5432"
  database: "postgres"
  schema: "public"
  maxconns: 10
  minconns: 1
  maxconnlifetime: 30
  maxconnidletime: 10
  healthcheckperiod: 5

info:  ## This is the information that will be displayed in the swagger
  name: "My-App"
  version: "1.0.0"
  description: "test service"
  title: "MyApp"
  terms: "https://example.com/terms"
  email: "test@gmail.com" ## This is the email address to contact the API maintainer and this reflects in swagger

server:
  bodylimit: 10485
  readbuffersize: 16384
  addr: ":8080"
  readtimeout: 10s
  writetimeout: 10s
  timeout: 40 ## Over all timeout for the request
  cors:       
    alloworigins:
      - "http://localhost:3000"
      - "http://localhost:8080"        
    allowheaders:
      - "Authorization"
      - "Content-Type"
      - "X-Request-Id"
    allowmethods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
  healthcheck: 
    endpoints:
      liveness:
      readiness:
log:
  level: "debug"
  format: "json"
  output: "stdout"

cron:
  scheduler:
    seconds: true                   # to allow seconds based cron jobs expressions (impact all jobs), disabled by default
    concurrency:
      limit:
        enabled: true               # to limit concurrent cron jobs executions, disabled by default
        max: 3                      # concurrency limit
        mode: wait                  # "wait" or "reschedule"
    stop:
      timeout: 5s                   # scheduler shutdown timeout for graceful cron jobs termination, 10 seconds by default
  jobs:                             # common cron jobs options
    execution:
      start:
        immediately: true           # to start cron jobs executions immediately (by default)
        #at: "2024-08-25T11:19:00Z"  # or a given date time (RFC3339)
        at: "2024-08-25T11:27:00+05:30"
      limit:
        enabled: true               # to limit the number of per cron jobs executions, disabled by default
        max: 3                      # executions limit
    singleton:
      enabled: true                 # to execute the cron jobs in singleton mode, disabled by default
      mode: wait                    # "wait" or "reschedule"
  log:
    enabled: true                   # to log cron jobs executions, disabled by default (errors will always be logged).
    exclude:                        # to exclude by name cron jobs from logging
      - foo
      - bar

client: 
  baseurl: "http://localhost:8080"
